"""Coleta: captura de páginas (evidência), leitura de preço/vaga/CNPJ, situação cadastral,
comprovante da Receita, gravação das observações e pendências (validade e comprovantes)."""

from orca.coleta.captura import Captura, ErroCaptura, Navegador, cabecalho_pdf, detectar_bloqueio, horario_brasilia
from orca.coleta.catalogo import (
    ATRIBUTOS_PADRAO,
    CATALOGO_PADRAO,
    JORNADAS_PADRAO,
    Jornada,
    LojaCatalogo,
    dominio_da_url,
    ler_catalogo,
    ler_jornadas,
    ler_vocabulario,
)
from orca.coleta.cnpj import PROVEDORES, DadosCnpj, ErroCnpj, consultar_cnpj
from orca.coleta.extracao import (
    ProdutoExtraido,
    VagaExtraida,
    cnpjs_no_texto,
    extrair_produto,
    extrair_vaga,
    objetos_jsonld,
    preco_aparece,
    precos_perto,
    precos_visiveis,
)
from orca.coleta.pendencias import (
    cnpjs_do_projeto,
    comprovante_valido,
    comprovantes_pendentes,
    conferir_validade,
    observacoes_do_projeto,
    vigentes,
)
from orca.coleta.receita import comprovante_na_tela, emitir_comprovante, url_do_comprovante
from orca.coleta.registro import (
    ResultadoColeta,
    coletar_cargo,
    coletar_item,
    fonte_da_url,
    refazer_pesquisa,
    registrar_captura,
    registrar_comprovante,
    registrar_consulta_cnpj,
    registrar_observacao_cargo,
    registrar_observacao_item,
    ultima_consulta,
    validar_cnpj,
)

__all__ = [
    "ATRIBUTOS_PADRAO",
    "CATALOGO_PADRAO",
    "JORNADAS_PADRAO",
    "PROVEDORES",
    "Captura",
    "DadosCnpj",
    "ErroCaptura",
    "ErroCnpj",
    "Jornada",
    "LojaCatalogo",
    "Navegador",
    "ProdutoExtraido",
    "ResultadoColeta",
    "VagaExtraida",
    "cabecalho_pdf",
    "cnpjs_do_projeto",
    "cnpjs_no_texto",
    "coletar_cargo",
    "coletar_item",
    "comprovante_na_tela",
    "comprovante_valido",
    "comprovantes_pendentes",
    "conferir_validade",
    "consultar_cnpj",
    "detectar_bloqueio",
    "dominio_da_url",
    "emitir_comprovante",
    "extrair_produto",
    "extrair_vaga",
    "fonte_da_url",
    "horario_brasilia",
    "ler_catalogo",
    "ler_jornadas",
    "ler_vocabulario",
    "objetos_jsonld",
    "observacoes_do_projeto",
    "preco_aparece",
    "precos_perto",
    "precos_visiveis",
    "refazer_pesquisa",
    "registrar_captura",
    "registrar_comprovante",
    "registrar_consulta_cnpj",
    "registrar_observacao_cargo",
    "registrar_observacao_item",
    "ultima_consulta",
    "url_do_comprovante",
    "validar_cnpj",
    "vigentes",
]
