"""Banco local (SQLite): tabelas, migrações, sessões com autor e perfis de regras gravados."""

from orca.banco.base import Base, agora, novo_id
from orca.banco.tabelas import (
    TABELAS_IMUTAVEIS,
    Alerta,
    Arquivo,
    Cargo,
    Comprovante,
    ConsultaCnpj,
    Correspondencia,
    Cotacao,
    CotacaoObservacao,
    Decisao,
    Evento,
    Evidencia,
    ExecucaoOtimizacao,
    Fonte,
    Item,
    LinhaFinal,
    Lote,
    Observacao,
    Orcamento,
    Organizacao,
    PerfilRegras,
    Projeto,
    Tarefa,
)
from orca.banco.conexao import (  # noqa: E402 — depois das tabelas (a auditoria depende delas)
    abrir_banco,
    atualizar_banco,
    copiar_banco,
    criar_engine,
    revisao_atual,
    revisao_mais_nova,
    sessao_como,
)
from orca.banco.correspondencias import (
    ErroCorrespondencia,
    anuncio_da_observacao,
    correspondencia_vigente,
    corresponder,
    decidir_correspondencia,
    especificacao_do_item,
    registrar_correspondencia,
    vale_como_verde,
)
from orca.banco.execucoes import registrar_execucao
from orca.banco.perfis import (
    camada_de,
    definir_camada_do_orcamento,
    definir_camadas_do_projeto,
    perfil_do_orcamento,
    perfil_do_projeto,
    registrar_camada,
)

__all__ = [
    "TABELAS_IMUTAVEIS",
    "Alerta",
    "Arquivo",
    "Base",
    "Cargo",
    "Comprovante",
    "ConsultaCnpj",
    "Correspondencia",
    "Cotacao",
    "CotacaoObservacao",
    "Decisao",
    "ErroCorrespondencia",
    "Evento",
    "Evidencia",
    "ExecucaoOtimizacao",
    "Fonte",
    "Item",
    "LinhaFinal",
    "Lote",
    "Observacao",
    "Orcamento",
    "Organizacao",
    "PerfilRegras",
    "Projeto",
    "Tarefa",
    "abrir_banco",
    "agora",
    "anuncio_da_observacao",
    "atualizar_banco",
    "camada_de",
    "copiar_banco",
    "correspondencia_vigente",
    "corresponder",
    "criar_engine",
    "decidir_correspondencia",
    "definir_camada_do_orcamento",
    "definir_camadas_do_projeto",
    "especificacao_do_item",
    "novo_id",
    "perfil_do_orcamento",
    "perfil_do_projeto",
    "registrar_camada",
    "registrar_correspondencia",
    "registrar_execucao",
    "revisao_atual",
    "revisao_mais_nova",
    "sessao_como",
    "vale_como_verde",
]
