"""Execuções do otimizador e linhas do orçamento final (etapa 5).

Revisão: 0002
Anterior: 0001
Criada em: 2026-09-23 01:32:39.980436

Lembrete: operações em modo batch recriam a tabela e perdem os gatilhos.
Depois delas, chame orca.banco.gatilhos.criar_gatilhos(op.execute, tabela, imutavel).
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from orca.banco.gatilhos import criar_gatilhos


revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucao_otimizacao',
    sa.Column('projeto_id', sa.String(length=32), nullable=False),
    sa.Column('impressao_regras', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('teto_centavos', sa.Integer(), nullable=False),
    sa.Column('total_centavos', sa.Integer(), nullable=True),
    sa.Column('verificacao_ok', sa.Boolean(), nullable=False),
    sa.Column('versao_otimizador', sa.String(length=40), nullable=False),
    sa.Column('entradas', sa.JSON(), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.CheckConstraint("status IN ('otima', 'viavel', 'sem_solucao')", name=op.f('ck_execucao_otimizacao_status')),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], name=op.f('fk_execucao_otimizacao_projeto_id_projeto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execucao_otimizacao'))
    )
    with op.batch_alter_table('execucao_otimizacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execucao_otimizacao_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('linha_final',
    sa.Column('execucao_id', sa.String(length=32), nullable=False),
    sa.Column('linha_id', sa.String(length=64), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=10), nullable=False),
    sa.Column('preco_unitario_centavos', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_hora_centavos', sa.Integer(), nullable=True),
    sa.Column('horas_centesimos', sa.Integer(), nullable=True),
    sa.Column('valor_mensal_centavos', sa.Integer(), nullable=True),
    sa.Column('postos', sa.Integer(), nullable=True),
    sa.Column('meses', sa.Integer(), nullable=False),
    sa.Column('total_centavos', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint("alvo_tipo IN ('item', 'cargo')", name=op.f('ck_linha_final_alvo')),
    sa.CheckConstraint('meses >= 1 AND total_centavos >= 0', name=op.f('ck_linha_final_valores')),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_otimizacao.id'], name=op.f('fk_linha_final_execucao_id_execucao_otimizacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linha_final'))
    )
    with op.batch_alter_table('linha_final', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linha_final_execucao_id'), ['execucao_id'], unique=False)

    # ### end Alembic commands ###

    # Tabelas imutáveis: não aceitam DELETE nem UPDATE (princípio 6).
    for tabela in ("execucao_otimizacao", "linha_final"):
        criar_gatilhos(op.execute, tabela, imutavel=True)


def downgrade() -> None:
    raise NotImplementedError("O Orça.AI não desfaz migrações; restaure a cópia de segurança.")
