"""Estrutura inicial: tabelas, restrições e gatilhos de proteção do histórico.

Revisão: 0001
Anterior: 
Criada em: 2026-09-23 01:09:14.918624

Lembrete: operações em modo batch recriam a tabela e perdem os gatilhos.
Depois delas, chame orca.banco.gatilhos.criar_gatilhos(op.execute, tabela, imutavel).
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from orca.banco.gatilhos import criar_gatilhos


revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivo',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('caminho', sa.String(length=300), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint('length(sha256) = 64', name=op.f('ck_arquivo_sha256')),
    sa.CheckConstraint('tamanho >= 0', name=op.f('ck_arquivo_tamanho')),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_arquivo'))
    )
    op.create_table('consulta_cnpj',
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=300), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=300), nullable=True),
    sa.Column('situacao', sa.String(length=40), nullable=True),
    sa.Column('data_situacao', sa.String(length=10), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('provedor', sa.String(length=40), nullable=False),
    sa.Column('consultado_em', sa.String(length=40), nullable=False),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consulta_cnpj'))
    )
    with op.batch_alter_table('consulta_cnpj', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consulta_cnpj_cnpj'), ['cnpj'], unique=False)

    op.create_table('decisao',
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=30), nullable=False),
    sa.Column('alvo_id', sa.String(length=64), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisao'))
    )
    with op.batch_alter_table('decisao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisao_alvo_id'), ['alvo_id'], unique=False)

    op.create_table('evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projeto_id', sa.String(length=32), nullable=True),
    sa.Column('entidade', sa.String(length=40), nullable=False),
    sa.Column('entidade_id', sa.String(length=64), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('depois', sa.JSON(), nullable=True),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento'))
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_entidade'), ['entidade', 'entidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('fonte',
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('dominio', sa.String(length=200), nullable=True),
    sa.Column('catalogo_id', sa.String(length=60), nullable=True),
    sa.Column('conector', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint("tipo IN ('loja', 'empresa', 'fornecedor', 'publica')", name=op.f('ck_fonte_tipo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fonte'))
    )
    op.create_table('organizacao',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizacao'))
    )
    op.create_table('comprovante',
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('arquivo_sha256', sa.String(length=64), nullable=False),
    sa.Column('emitido_em', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_sha256'], ['arquivo.sha256'], name=op.f('fk_comprovante_arquivo_sha256_arquivo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comprovante'))
    )
    with op.batch_alter_table('comprovante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprovante_cnpj'), ['cnpj'], unique=False)

    op.create_table('evidencia',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('capturado_em', sa.String(length=40), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('png_sha256', sa.String(length=64), nullable=True),
    sa.Column('html_sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['html_sha256'], ['arquivo.sha256'], name=op.f('fk_evidencia_html_sha256_arquivo')),
    sa.ForeignKeyConstraint(['pdf_sha256'], ['arquivo.sha256'], name=op.f('fk_evidencia_pdf_sha256_arquivo')),
    sa.ForeignKeyConstraint(['png_sha256'], ['arquivo.sha256'], name=op.f('fk_evidencia_png_sha256_arquivo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidencia'))
    )
    op.create_table('perfil_regras',
    sa.Column('organizacao_id', sa.String(length=32), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('impressao', sa.String(length=64), nullable=False),
    sa.Column('conteudo_yaml', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint("(nivel = 'sistema') = (organizacao_id IS NULL)", name=op.f('ck_perfil_regras_sistema_sem_organizacao')),
    sa.CheckConstraint("nivel IN ('sistema', 'osc', 'secretaria', 'projeto', 'orcamento')", name=op.f('ck_perfil_regras_nivel')),
    sa.CheckConstraint('versao >= 1', name=op.f('ck_perfil_regras_versao')),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacao.id'], name=op.f('fk_perfil_regras_organizacao_id_organizacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perfil_regras')),
    sa.UniqueConstraint('organizacao_id', 'nome', 'versao', name=op.f('uq_perfil_regras_organizacao_id_nome_versao'))
    )
    op.create_table('projeto',
    sa.Column('organizacao_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('orgao', sa.String(length=300), nullable=True),
    sa.Column('instrumento', sa.String(length=100), nullable=True),
    sa.Column('processo', sa.String(length=100), nullable=True),
    sa.Column('teto_centavos', sa.Integer(), nullable=False),
    sa.Column('duracao_meses', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('data_entrega', sa.String(length=10), nullable=True),
    sa.Column('camadas_regras', sa.JSON(), nullable=False),
    sa.Column('arquivado_em', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('excluido_em', sa.String(length=40), nullable=True),
    sa.CheckConstraint('duracao_meses BETWEEN 1 AND 120', name=op.f('ck_projeto_duracao')),
    sa.CheckConstraint('teto_centavos > 0', name=op.f('ck_projeto_teto')),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacao.id'], name=op.f('fk_projeto_organizacao_id_organizacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projeto'))
    )
    op.create_table('alerta',
    sa.Column('projeto_id', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('severidade', sa.String(length=10), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=30), nullable=True),
    sa.Column('alvo_id', sa.String(length=64), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('resolvido_em', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint("severidade IN ('info', 'atencao', 'problema')", name=op.f('ck_alerta_severidade')),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], name=op.f('fk_alerta_projeto_id_projeto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerta'))
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerta_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('orcamento',
    sa.Column('projeto_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('camada_regras_id', sa.String(length=32), nullable=True),
    sa.Column('arquivado_em', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('excluido_em', sa.String(length=40), nullable=True),
    sa.CheckConstraint("tipo IN ('materiais', 'mao_de_obra', 'servicos')", name=op.f('ck_orcamento_tipo')),
    sa.ForeignKeyConstraint(['camada_regras_id'], ['perfil_regras.id'], name=op.f('fk_orcamento_camada_regras_id_perfil_regras')),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], name=op.f('fk_orcamento_projeto_id_projeto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orcamento'))
    )
    op.create_table('cargo',
    sa.Column('orcamento_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cbo', sa.String(length=10), nullable=True),
    sa.Column('postos', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('jornada_id', sa.String(length=60), nullable=False),
    sa.Column('horas_planejadas_centesimos', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('excluido_em', sa.String(length=40), nullable=True),
    sa.Column('mes_inicio', sa.Integer(), nullable=False),
    sa.Column('mes_fim', sa.Integer(), nullable=False),
    sa.Column('margem_min_percentual', sa.Integer(), nullable=True),
    sa.Column('margem_max_percentual', sa.Integer(), nullable=True),
    sa.Column('travado', sa.Boolean(), nullable=False),
    sa.CheckConstraint("regime IN ('mei', 'recibo', 'clt')", name=op.f('ck_cargo_regime')),
    sa.CheckConstraint('horas_planejadas_centesimos > 0', name=op.f('ck_cargo_horas')),
    sa.CheckConstraint('margem_max_percentual IS NULL OR margem_max_percentual BETWEEN 0 AND 1000', name=op.f('ck_cargo_margem_max')),
    sa.CheckConstraint('margem_min_percentual IS NULL OR margem_min_percentual BETWEEN -100 AND 0', name=op.f('ck_cargo_margem_min')),
    sa.CheckConstraint('mes_inicio >= 1 AND mes_fim >= mes_inicio', name=op.f('ck_cargo_meses')),
    sa.CheckConstraint('postos >= 1', name=op.f('ck_cargo_postos')),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], name=op.f('fk_cargo_orcamento_id_orcamento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo'))
    )
    op.create_table('lote',
    sa.Column('orcamento_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('excluido_em', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], name=op.f('fk_lote_orcamento_id_orcamento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lote'))
    )
    op.create_table('item',
    sa.Column('lote_id', sa.String(length=32), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('apresentacao', sa.String(length=200), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('catmat', sa.String(length=20), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('qtd_planejada', sa.Integer(), nullable=False),
    sa.Column('substitui_item_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('excluido_em', sa.String(length=40), nullable=True),
    sa.Column('mes_inicio', sa.Integer(), nullable=False),
    sa.Column('mes_fim', sa.Integer(), nullable=False),
    sa.Column('margem_min_percentual', sa.Integer(), nullable=True),
    sa.Column('margem_max_percentual', sa.Integer(), nullable=True),
    sa.Column('travado', sa.Boolean(), nullable=False),
    sa.CheckConstraint('margem_max_percentual IS NULL OR margem_max_percentual BETWEEN 0 AND 1000', name=op.f('ck_item_margem_max')),
    sa.CheckConstraint('margem_min_percentual IS NULL OR margem_min_percentual BETWEEN -100 AND 0', name=op.f('ck_item_margem_min')),
    sa.CheckConstraint('mes_inicio >= 1 AND mes_fim >= mes_inicio', name=op.f('ck_item_meses')),
    sa.CheckConstraint('qtd_planejada >= 0', name=op.f('ck_item_quantidade')),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('fk_item_lote_id_lote')),
    sa.ForeignKeyConstraint(['substitui_item_id'], ['item.id'], name=op.f('fk_item_substitui_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_table('cotacao',
    sa.Column('alvo_tipo', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('cargo_id', sa.String(length=32), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('soma_centavos', sa.Integer(), nullable=False),
    sa.Column('media_exibida_centavos', sa.Integer(), nullable=False),
    sa.Column('impressao_regras', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.CheckConstraint("(alvo_tipo = 'item' AND item_id IS NOT NULL AND cargo_id IS NULL) OR (alvo_tipo = 'cargo' AND cargo_id IS NOT NULL AND item_id IS NULL)", name=op.f('ck_cotacao_alvo')),
    sa.CheckConstraint('n >= 1 AND soma_centavos > 0 AND media_exibida_centavos > 0', name=op.f('ck_cotacao_valores')),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], name=op.f('fk_cotacao_cargo_id_cargo')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_cotacao_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotacao'))
    )
    with op.batch_alter_table('cotacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotacao_cargo_id'), ['cargo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cotacao_item_id'), ['item_id'], unique=False)

    op.create_table('observacao',
    sa.Column('alvo_tipo', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('cargo_id', sa.String(length=32), nullable=True),
    sa.Column('fonte_id', sa.String(length=32), nullable=False),
    sa.Column('cnpj_vendedor', sa.String(length=14), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('apresentacao', sa.String(length=200), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('preco_centavos', sa.Integer(), nullable=True),
    sa.Column('salario_min_centavos', sa.Integer(), nullable=True),
    sa.Column('salario_max_centavos', sa.Integer(), nullable=True),
    sa.Column('encontrado', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('coletado_em', sa.String(length=40), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('evidencia_id', sa.String(length=32), nullable=True),
    sa.Column('preco_no_html', sa.Boolean(), nullable=True),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.CheckConstraint("(alvo_tipo = 'item' AND item_id IS NOT NULL AND cargo_id IS NULL) OR (alvo_tipo = 'cargo' AND cargo_id IS NOT NULL AND item_id IS NULL)", name=op.f('ck_observacao_alvo')),
    sa.CheckConstraint('preco_centavos IS NULL OR preco_centavos > 0', name=op.f('ck_observacao_preco')),
    sa.CheckConstraint('salario_min_centavos IS NULL OR salario_max_centavos IS NULL OR salario_min_centavos <= salario_max_centavos', name=op.f('ck_observacao_faixa_salarial')),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], name=op.f('fk_observacao_cargo_id_cargo')),
    sa.ForeignKeyConstraint(['evidencia_id'], ['evidencia.id'], name=op.f('fk_observacao_evidencia_id_evidencia')),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], name=op.f('fk_observacao_fonte_id_fonte')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_observacao_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observacao'))
    )
    with op.batch_alter_table('observacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observacao_cargo_id'), ['cargo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observacao_item_id'), ['item_id'], unique=False)

    op.create_table('correspondencia',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('observacao_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('motivos', sa.JSON(), nullable=False),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.CheckConstraint("NOT (status = 'verde' AND origem = 'ia')", name=op.f('ck_correspondencia_ia_nao_promove')),
    sa.CheckConstraint("origem IN ('ean', 'atributos', 'ia', 'humano')", name=op.f('ck_correspondencia_origem')),
    sa.CheckConstraint("status IN ('verde', 'amarelo', 'vermelho')", name=op.f('ck_correspondencia_status')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_correspondencia_item_id_item')),
    sa.ForeignKeyConstraint(['observacao_id'], ['observacao.id'], name=op.f('fk_correspondencia_observacao_id_observacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correspondencia'))
    )
    with op.batch_alter_table('correspondencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correspondencia_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correspondencia_observacao_id'), ['observacao_id'], unique=False)

    op.create_table('cotacao_observacao',
    sa.Column('cotacao_id', sa.String(length=32), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('observacao_id', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint('ordem >= 1', name=op.f('ck_cotacao_observacao_ordem')),
    sa.ForeignKeyConstraint(['cotacao_id'], ['cotacao.id'], name=op.f('fk_cotacao_observacao_cotacao_id_cotacao')),
    sa.ForeignKeyConstraint(['observacao_id'], ['observacao.id'], name=op.f('fk_cotacao_observacao_observacao_id_observacao')),
    sa.PrimaryKeyConstraint('cotacao_id', 'ordem', name=op.f('pk_cotacao_observacao'))
    )
    # ### end Alembic commands ###

    # Gatilhos (princípio 6): nenhuma tabela aceita DELETE; as imutáveis não aceitam UPDATE.
    imutaveis = {
        "arquivo", "comprovante", "consulta_cnpj", "correspondencia", "cotacao",
        "cotacao_observacao", "decisao", "evento", "evidencia", "observacao", "perfil_regras",
    }
    todas = [
        "alerta", "arquivo", "cargo", "comprovante", "consulta_cnpj", "correspondencia", "cotacao",
        "cotacao_observacao", "decisao", "evento", "evidencia", "fonte", "item", "lote", "observacao",
        "orcamento", "organizacao", "perfil_regras", "projeto",
    ]
    for tabela in todas:
        criar_gatilhos(op.execute, tabela, tabela in imutaveis)


def downgrade() -> None:
    raise NotImplementedError("O Orca.AI não desfaz migrações; restaure a cópia de segurança.")
